---
- name: Install office
  become: true
  when:
    - office
  block:
    - name: Install office | Install office packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: false
      loop:
        - "{{ spelling_packages }}"
        - "{{ office_packages }}"

    - name: Install office | Deleting downloaded packages that are no longer required
      ansible.builtin.apt:
        clean: true
