---
# General

### GRUB
grub_cmdline_linux_default: "{{ 'quiet splash acpi_backlight=native' if DESTINATION_DEVICE == 'laptop' else 'quiet splash' }}"
grub_default_config: /etc/default/grub

# Shell
shell_package_name: zsh
shell_config: .zshrc
oh_my_zsh_tmp: /tmp/.oh-my-zsh
my_zsh_theme_file: jispwoso-nuxster.zsh-theme

# Sysctl

### SDD
ssd_sysctl:
  vm.vfs_cache_pressure: 50
  vm.swappiness: 10
  vm.dirty_ratio: 10
  vm.dirty_background_ratio: 5

# APT
apt_config_file: /etc/apt/apt.conf

### APT Options
apt_options:
  - 'APT::Install-Recommends "false";'
  - 'APT::Install-Suggests "false";'
  - 'APT::Default-Release "/^stable(|-security|-updates)$/";'
