---
- name: Install packages
  ansible.builtin.include_tasks:
    file: install_packages.yml

- name: Configure users and groups
  ansible.builtin.include_tasks:
    file: configure_users_and_groups.yml
