---
# CPU manufacturer: intel or amd
CPU: intel

# Are you on: desktop, laptop or vm
DESTINATION_DEVICE: desktop

# The name of your user in the system
USERNAME: nuxster

# User's shell
SHELL: fish

# User's timezone
TIMEZONE: Europe/Moscow

# Is there an SSD device in the system
SSD_DEVICES: true

# Install Libre Office packages
OFFICE: false

# Install hypervisor (QEMU/Libvirt)
HYPERVISOR: false

# Install neovim packages
INSTALL_NEOVIM: true

# Upgrade all packages
UPGRADE_PACKAGES: true

# Install ntp daemon (ntpd/chrony) packages
NTP_DAEMON: true

# Configure networking
RECONFIGURE_NETWORK: true

# Path to thermal zone
PATH_TO_THERMAL_ZONE: /sys/class/hwmon/hwmon2/temp1_input

# Configure displays
DISPLAYS_PARAMETERS:
  - name: eDP-1
    width: 3840
    height: 2160
    rate: 60
    scale: 2
  - name: HDMI-A-1
    width: 3840
    height: 2160
    rate: 60
    scale: 2

# APT sourve mirror
APT_SOURCE_MIRROR_URL: mirror.yandex.ru
