---
- name: Configure laptop
  when:
    - DESTINATION_DEVICE == 'laptop'
  become: true
  block:
    - name: Install packages for laptop
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: false
      loop: "{{ for_laptop_packages }}"
    
    - name: Configure TLP
      ansible.builtin.copy:
        src: "etc/tlp.d/{{ tlp_config_file }}"
        dest: "/etc/tlp.d/{{ tlp_config_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: TLP changed configuration apply
      ansible.builtin.command:
        cmd: /usr/sbin/tlp start
