---
- name: Install hypervisor packages
  ansible.builtin.include_tasks:
    file: install_packages.yml

- name: Configure hupervisor
  ansible.builtin.include_tasks:
    file: configure_hypervisor.yml
